/* PROJECTS */
export const GET_SECTOR_INFORMATION = "GET_SECTOR_INFORMATION";
export const GET_SECTOR_INFORMATION_SUCCESS = "GET_SECTOR_INFORMATION_SUCCESS";
export const GET_SECTOR_INFORMATION_FAIL = "GET_SECTOR_INFORMATION_FAIL";

/**
 * add PROJECT
 */
export const ADD_SECTOR_INFORMATION = "ADD_SECTOR_INFORMATION";
export const ADD_SECTOR_INFORMATION_SUCCESS = "ADD_SECTOR_INFORMATION_SUCCESS";
export const ADD_SECTOR_INFORMATION_FAIL = "ADD_SECTOR_INFORMATION_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_SECTOR_INFORMATION = "UPDATE_SECTOR_INFORMATION";
export const UPDATE_SECTOR_INFORMATION_SUCCESS = "UPDATE_SECTOR_INFORMATION_SUCCESS";
export const UPDATE_SECTOR_INFORMATION_FAIL = "UPDATE_SECTOR_INFORMATION_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_SECTOR_INFORMATION = "DELETE_SECTOR_INFORMATION";
export const DELETE_SECTOR_INFORMATION_SUCCESS = "DELETE_SECTOR_INFORMATION_SUCCESS";
export const DELETE_SECTOR_INFORMATION_FAIL = "DELETE_SECTOR_INFORMATION_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
