/* PROJECTS */
export const GET_BUDGET_SOURCE = "GET_BUDGET_SOURCE";
export const GET_BUDGET_SOURCE_SUCCESS = "GET_BUDGET_SOURCE_SUCCESS";
export const GET_BUDGET_SOURCE_FAIL = "GET_BUDGET_SOURCE_FAIL";

/**
 * add PROJECT
 */
export const ADD_BUDGET_SOURCE = "ADD_BUDGET_SOURCE";
export const ADD_BUDGET_SOURCE_SUCCESS = "ADD_BUDGET_SOURCE_SUCCESS";
export const ADD_BUDGET_SOURCE_FAIL = "ADD_BUDGET_SOURCE_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_BUDGET_SOURCE = "UPDATE_BUDGET_SOURCE";
export const UPDATE_BUDGET_SOURCE_SUCCESS = "UPDATE_BUDGET_SOURCE_SUCCESS";
export const UPDATE_BUDGET_SOURCE_FAIL = "UPDATE_BUDGET_SOURCE_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_BUDGET_SOURCE = "DELETE_BUDGET_SOURCE";
export const DELETE_BUDGET_SOURCE_SUCCESS = "DELETE_BUDGET_SOURCE_SUCCESS";
export const DELETE_BUDGET_SOURCE_FAIL = "DELETE_BUDGET_SOURCE_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
