// src/redux/actionTypes.js
export const FETCH_PROJECTSTREE_REQUEST = 'FETCH_PROJECTSTREE_REQUEST';
export const FETCH_PROJECTSTREE_SUCCESS = 'FETCH_PROJECTSTREE_SUCCESS';
export const FETCH_PROJECTSTREE_FAILURE = 'FETCH_PROJECTSTREE_FAILURE';

export const DELETE_PROJECTFOLDER_REQUEST = 'DELETE_PROJECTFOLDER_REQUEST';
export const DELETE_PROJECTFOLDER_SUCCESS = 'DELETE_PROJECTFOLDER_SUCCESS';
export const DELETE_PROJECTFOLDER_FAILURE = 'DELETE_PROJECTFOLDER_FAILURE';

export const ADD_PROJECTFOLDER_REQUEST = 'ADD_PROJECTFOLDER_REQUEST';
export const ADD_PROJECTFOLDER_SUCCESS = 'ADD_PROJECTFOLDER_SUCCESS';
export const ADD_PROJECTFOLDER_FAILURE = 'ADD_PROJECTFOLDER_FAILURE';

export const RENAME_PROJECTFOLDER_REQUEST = 'RENAME_PROJECTFOLDER_REQUEST';
export const RENAME_PROJECTFOLDER_SUCCESS = 'RENAME_PROJECTFOLDER_SUCCESS';
export const RENAME_PROJECTFOLDER_FAILURE = 'RENAME_PROJECTFOLDER_FAILURE';
