/* PROJECTS */
export const GET_ACCESS_LOG = "GET_ACCESS_LOG";
export const GET_ACCESS_LOG_SUCCESS = "GET_ACCESS_LOG_SUCCESS";
export const GET_ACCESS_LOG_FAIL = "GET_ACCESS_LOG_FAIL";

/**
 * add PROJECT
 */
export const ADD_ACCESS_LOG = "ADD_ACCESS_LOG";
export const ADD_ACCESS_LOG_SUCCESS = "ADD_ACCESS_LOG_SUCCESS";
export const ADD_ACCESS_LOG_FAIL = "ADD_ACCESS_LOG_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_ACCESS_LOG = "UPDATE_ACCESS_LOG";
export const UPDATE_ACCESS_LOG_SUCCESS = "UPDATE_ACCESS_LOG_SUCCESS";
export const UPDATE_ACCESS_LOG_FAIL = "UPDATE_ACCESS_LOG_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_ACCESS_LOG = "DELETE_ACCESS_LOG";
export const DELETE_ACCESS_LOG_SUCCESS = "DELETE_ACCESS_LOG_SUCCESS";
export const DELETE_ACCESS_LOG_FAIL = "DELETE_ACCESS_LOG_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
