/* PROJECTS */
export const GET_PROJECT_PAYMENT = "GET_PROJECT_PAYMENT";
export const GET_PROJECT_PAYMENT_SUCCESS = "GET_PROJECT_PAYMENT_SUCCESS";
export const GET_PROJECT_PAYMENT_FAIL = "GET_PROJECT_PAYMENT_FAIL";

/**
 * add PROJECT
 */
export const ADD_PROJECT_PAYMENT = "ADD_PROJECT_PAYMENT";
export const ADD_PROJECT_PAYMENT_SUCCESS = "ADD_PROJECT_PAYMENT_SUCCESS";
export const ADD_PROJECT_PAYMENT_FAIL = "ADD_PROJECT_PAYMENT_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_PROJECT_PAYMENT = "UPDATE_PROJECT_PAYMENT";
export const UPDATE_PROJECT_PAYMENT_SUCCESS = "UPDATE_PROJECT_PAYMENT_SUCCESS";
export const UPDATE_PROJECT_PAYMENT_FAIL = "UPDATE_PROJECT_PAYMENT_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_PROJECT_PAYMENT = "DELETE_PROJECT_PAYMENT";
export const DELETE_PROJECT_PAYMENT_SUCCESS = "DELETE_PROJECT_PAYMENT_SUCCESS";
export const DELETE_PROJECT_PAYMENT_FAIL = "DELETE_PROJECT_PAYMENT_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
