/* PROJECTS */
export const GET_BUDGET_YEAR = "GET_BUDGET_YEAR";
export const GET_BUDGET_YEAR_SUCCESS = "GET_BUDGET_YEAR_SUCCESS";
export const GET_BUDGET_YEAR_FAIL = "GET_BUDGET_YEAR_FAIL";

/**
 * add PROJECT
 */
export const ADD_BUDGET_YEAR = "ADD_BUDGET_YEAR";
export const ADD_BUDGET_YEAR_SUCCESS = "ADD_BUDGET_YEAR_SUCCESS";
export const ADD_BUDGET_YEAR_FAIL = "ADD_BUDGET_YEAR_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_BUDGET_YEAR = "UPDATE_BUDGET_YEAR";
export const UPDATE_BUDGET_YEAR_SUCCESS = "UPDATE_BUDGET_YEAR_SUCCESS";
export const UPDATE_BUDGET_YEAR_FAIL = "UPDATE_BUDGET_YEAR_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_BUDGET_YEAR = "DELETE_BUDGET_YEAR";
export const DELETE_BUDGET_YEAR_SUCCESS = "DELETE_BUDGET_YEAR_SUCCESS";
export const DELETE_BUDGET_YEAR_FAIL = "DELETE_BUDGET_YEAR_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
