/* PROJECTS */
export const GET_BUDGET_REQUEST = "GET_BUDGET_REQUEST";
export const GET_BUDGET_REQUEST_SUCCESS = "GET_BUDGET_REQUEST_SUCCESS";
export const GET_BUDGET_REQUEST_FAIL = "GET_BUDGET_REQUEST_FAIL";

/**
 * add PROJECT
 */
export const ADD_BUDGET_REQUEST = "ADD_BUDGET_REQUEST";
export const ADD_BUDGET_REQUEST_SUCCESS = "ADD_BUDGET_REQUEST_SUCCESS";
export const ADD_BUDGET_REQUEST_FAIL = "ADD_BUDGET_REQUEST_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_BUDGET_REQUEST = "UPDATE_BUDGET_REQUEST";
export const UPDATE_BUDGET_REQUEST_SUCCESS = "UPDATE_BUDGET_REQUEST_SUCCESS";
export const UPDATE_BUDGET_REQUEST_FAIL = "UPDATE_BUDGET_REQUEST_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_BUDGET_REQUEST = "DELETE_BUDGET_REQUEST";
export const DELETE_BUDGET_REQUEST_SUCCESS = "DELETE_BUDGET_REQUEST_SUCCESS";
export const DELETE_BUDGET_REQUEST_FAIL = "DELETE_BUDGET_REQUEST_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
