export const PERFORM_SEARCH_REQUEST = "PERFORM_SEARCH_REQUEST";
export const PERFORM_SEARCH_SUCCESS = "PERFORM_SEARCH_SUCCESS";
export const PERFORM_SEARCH_FAIL = "PERFORM_SEARCH_FAIL";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
export const DELETE_SEARCH_RESULT = "DELETE_SEARCH_RESULT";
