/* PROJECTS */
export const GET_PROJECT_CONTRACTOR = "GET_PROJECT_CONTRACTOR";
export const GET_PROJECT_CONTRACTOR_SUCCESS = "GET_PROJECT_CONTRACTOR_SUCCESS";
export const GET_PROJECT_CONTRACTOR_FAIL = "GET_PROJECT_CONTRACTOR_FAIL";

/**
 * add PROJECT
 */
export const ADD_PROJECT_CONTRACTOR = "ADD_PROJECT_CONTRACTOR";
export const ADD_PROJECT_CONTRACTOR_SUCCESS = "ADD_PROJECT_CONTRACTOR_SUCCESS";
export const ADD_PROJECT_CONTRACTOR_FAIL = "ADD_PROJECT_CONTRACTOR_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_PROJECT_CONTRACTOR = "UPDATE_PROJECT_CONTRACTOR";
export const UPDATE_PROJECT_CONTRACTOR_SUCCESS = "UPDATE_PROJECT_CONTRACTOR_SUCCESS";
export const UPDATE_PROJECT_CONTRACTOR_FAIL = "UPDATE_PROJECT_CONTRACTOR_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_PROJECT_CONTRACTOR = "DELETE_PROJECT_CONTRACTOR";
export const DELETE_PROJECT_CONTRACTOR_SUCCESS = "DELETE_PROJECT_CONTRACTOR_SUCCESS";
export const DELETE_PROJECT_CONTRACTOR_FAIL = "DELETE_PROJECT_CONTRACTOR_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
