// actionTypes.js
export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE";
export const MARK_NOTIFICATIONS_AS_READ_REQUEST = "MARK_NOTIFICATIONS_AS_READ_REQUEST";
export const MARK_NOTIFICATIONS_AS_READ_SUCCESS = "MARK_NOTIFICATIONS_AS_READ_SUCCESS";
export const MARK_NOTIFICATIONS_AS_READ_FAILURE = "MARK_NOTIFICATIONS_AS_READ_FAILURE";
