/* PROJECTS */
export const GET_SECTOR_CATEGORY = "GET_SECTOR_CATEGORY";
export const GET_SECTOR_CATEGORY_SUCCESS = "GET_SECTOR_CATEGORY_SUCCESS";
export const GET_SECTOR_CATEGORY_FAIL = "GET_SECTOR_CATEGORY_FAIL";

/**
 * add PROJECT
 */
export const ADD_SECTOR_CATEGORY = "ADD_SECTOR_CATEGORY";
export const ADD_SECTOR_CATEGORY_SUCCESS = "ADD_SECTOR_CATEGORY_SUCCESS";
export const ADD_SECTOR_CATEGORY_FAIL = "ADD_SECTOR_CATEGORY_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_SECTOR_CATEGORY = "UPDATE_SECTOR_CATEGORY";
export const UPDATE_SECTOR_CATEGORY_SUCCESS = "UPDATE_SECTOR_CATEGORY_SUCCESS";
export const UPDATE_SECTOR_CATEGORY_FAIL = "UPDATE_SECTOR_CATEGORY_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_SECTOR_CATEGORY = "DELETE_SECTOR_CATEGORY";
export const DELETE_SECTOR_CATEGORY_SUCCESS = "DELETE_SECTOR_CATEGORY_SUCCESS";
export const DELETE_SECTOR_CATEGORY_FAIL = "DELETE_SECTOR_CATEGORY_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
