/* PROJECTS */
export const GET_DOCUMENT_TYPE = "GET_DOCUMENT_TYPE";
export const GET_DOCUMENT_TYPE_SUCCESS = "GET_DOCUMENT_TYPE_SUCCESS";
export const GET_DOCUMENT_TYPE_FAIL = "GET_DOCUMENT_TYPE_FAIL";

/**
 * add PROJECT
 */
export const ADD_DOCUMENT_TYPE = "ADD_DOCUMENT_TYPE";
export const ADD_DOCUMENT_TYPE_SUCCESS = "ADD_DOCUMENT_TYPE_SUCCESS";
export const ADD_DOCUMENT_TYPE_FAIL = "ADD_DOCUMENT_TYPE_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_DOCUMENT_TYPE = "UPDATE_DOCUMENT_TYPE";
export const UPDATE_DOCUMENT_TYPE_SUCCESS = "UPDATE_DOCUMENT_TYPE_SUCCESS";
export const UPDATE_DOCUMENT_TYPE_FAIL = "UPDATE_DOCUMENT_TYPE_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_DOCUMENT_TYPE = "DELETE_DOCUMENT_TYPE";
export const DELETE_DOCUMENT_TYPE_SUCCESS = "DELETE_DOCUMENT_TYPE_SUCCESS";
export const DELETE_DOCUMENT_TYPE_FAIL = "DELETE_DOCUMENT_TYPE_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
