/* PROJECTS */
export const GET_PROJECT_CATEGORY = "GET_PROJECT_CATEGORY";
export const GET_PROJECT_CATEGORY_SUCCESS = "GET_PROJECT_CATEGORY_SUCCESS";
export const GET_PROJECT_CATEGORY_FAIL = "GET_PROJECT_CATEGORY_FAIL";

/**
 * add PROJECT
 */
export const ADD_PROJECT_CATEGORY = "ADD_PROJECT_CATEGORY";
export const ADD_PROJECT_CATEGORY_SUCCESS = "ADD_PROJECT_CATEGORY_SUCCESS";
export const ADD_PROJECT_CATEGORY_FAIL = "ADD_PROJECT_CATEGORY_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_PROJECT_CATEGORY = "UPDATE_PROJECT_CATEGORY";
export const UPDATE_PROJECT_CATEGORY_SUCCESS = "UPDATE_PROJECT_CATEGORY_SUCCESS";
export const UPDATE_PROJECT_CATEGORY_FAIL = "UPDATE_PROJECT_CATEGORY_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_PROJECT_CATEGORY = "DELETE_PROJECT_CATEGORY";
export const DELETE_PROJECT_CATEGORY_SUCCESS = "DELETE_PROJECT_CATEGORY_SUCCESS";
export const DELETE_PROJECT_CATEGORY_FAIL = "DELETE_PROJECT_CATEGORY_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
