/* PROJECTS */
export const GET_CONTRACT_TERMINATION_REASON = "GET_CONTRACT_TERMINATION_REASON";
export const GET_CONTRACT_TERMINATION_REASON_SUCCESS = "GET_CONTRACT_TERMINATION_REASON_SUCCESS";
export const GET_CONTRACT_TERMINATION_REASON_FAIL = "GET_CONTRACT_TERMINATION_REASON_FAIL";

/**
 * add PROJECT
 */
export const ADD_CONTRACT_TERMINATION_REASON = "ADD_CONTRACT_TERMINATION_REASON";
export const ADD_CONTRACT_TERMINATION_REASON_SUCCESS = "ADD_CONTRACT_TERMINATION_REASON_SUCCESS";
export const ADD_CONTRACT_TERMINATION_REASON_FAIL = "ADD_CONTRACT_TERMINATION_REASON_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_CONTRACT_TERMINATION_REASON = "UPDATE_CONTRACT_TERMINATION_REASON";
export const UPDATE_CONTRACT_TERMINATION_REASON_SUCCESS = "UPDATE_CONTRACT_TERMINATION_REASON_SUCCESS";
export const UPDATE_CONTRACT_TERMINATION_REASON_FAIL = "UPDATE_CONTRACT_TERMINATION_REASON_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_CONTRACT_TERMINATION_REASON = "DELETE_CONTRACT_TERMINATION_REASON";
export const DELETE_CONTRACT_TERMINATION_REASON_SUCCESS = "DELETE_CONTRACT_TERMINATION_REASON_SUCCESS";
export const DELETE_CONTRACT_TERMINATION_REASON_FAIL = "DELETE_CONTRACT_TERMINATION_REASON_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
