/* PROJECTS */
export const GET_USER_ROLE = "GET_USER_ROLE";
export const GET_USER_ROLE_SUCCESS = "GET_USER_ROLE_SUCCESS";
export const GET_USER_ROLE_FAIL = "GET_USER_ROLE_FAIL";

/**
 * add PROJECT
 */
export const ADD_USER_ROLE = "ADD_USER_ROLE";
export const ADD_USER_ROLE_SUCCESS = "ADD_USER_ROLE_SUCCESS";
export const ADD_USER_ROLE_FAIL = "ADD_USER_ROLE_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAIL = "UPDATE_USER_ROLE_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_USER_ROLE = "DELETE_USER_ROLE";
export const DELETE_USER_ROLE_SUCCESS = "DELETE_USER_ROLE_SUCCESS";
export const DELETE_USER_ROLE_FAIL = "DELETE_USER_ROLE_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
