/* PROJECTS */
export const GET_STAKEHOLDER_TYPE = "GET_STAKEHOLDER_TYPE";
export const GET_STAKEHOLDER_TYPE_SUCCESS = "GET_STAKEHOLDER_TYPE_SUCCESS";
export const GET_STAKEHOLDER_TYPE_FAIL = "GET_STAKEHOLDER_TYPE_FAIL";

/**
 * add PROJECT
 */
export const ADD_STAKEHOLDER_TYPE = "ADD_STAKEHOLDER_TYPE";
export const ADD_STAKEHOLDER_TYPE_SUCCESS = "ADD_STAKEHOLDER_TYPE_SUCCESS";
export const ADD_STAKEHOLDER_TYPE_FAIL = "ADD_STAKEHOLDER_TYPE_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_STAKEHOLDER_TYPE = "UPDATE_STAKEHOLDER_TYPE";
export const UPDATE_STAKEHOLDER_TYPE_SUCCESS = "UPDATE_STAKEHOLDER_TYPE_SUCCESS";
export const UPDATE_STAKEHOLDER_TYPE_FAIL = "UPDATE_STAKEHOLDER_TYPE_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_STAKEHOLDER_TYPE = "DELETE_STAKEHOLDER_TYPE";
export const DELETE_STAKEHOLDER_TYPE_SUCCESS = "DELETE_STAKEHOLDER_TYPE_SUCCESS";
export const DELETE_STAKEHOLDER_TYPE_FAIL = "DELETE_STAKEHOLDER_TYPE_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
