/* PROJECTS */
export const GET_PROJECTS_STATUS = "GET_PROJECTS_STATUS";
export const GET_PROJECTS_STATUS_SUCCESS = "GET_PROJECTS_STATUS_SUCCESS";
export const GET_PROJECTS_STATUS_FAIL = "GET_PROJECTS_STATUS_FAIL";

/**
 * add PROJECT
 */
export const ADD_NEW_PROJECT_STATUS = "ADD_NEW_PROJECT_STATUS";
export const ADD_PROJECT_STATUS_SUCCESS = "ADD_PROJECT_STATUS_SUCCESS";
export const ADD_PROJECT_STATUS_FAIL = "ADD_PROJECT_STATUS_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_PROJECT_STATUS = "UPDATE_PROJECT_STATUS";
export const UPDATE_PROJECT_STATUS_SUCCESS = "UPDATE_PROJECT_STATUS_SUCCESS";
export const UPDATE_PROJECT_STATUS_FAIL = "UPDATE_PROJECT_STATUS_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_PROJECT_STATUS = "DELETE_PROJECT_STATUS";
export const DELETE_PROJECT_STATUS_SUCCESS = "DELETE_PROJECT_STATUS_SUCCESS";
export const DELETE_PROJECT_STATUS_FAIL = "DELETE_PROJECT_STATUS_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
export const TOGGLE_SHOW_RESULT = "TOGGLE_SHOW_RESULT";
