/* PROJECTS */
export const GET_CONTRACTOR_TYPE = "GET_CONTRACTOR_TYPE";
export const GET_CONTRACTOR_TYPE_SUCCESS = "GET_CONTRACTOR_TYPE_SUCCESS";
export const GET_CONTRACTOR_TYPE_FAIL = "GET_CONTRACTOR_TYPE_FAIL";

/**
 * add PROJECT
 */
export const ADD_CONTRACTOR_TYPE = "ADD_CONTRACTOR_TYPE";
export const ADD_CONTRACTOR_TYPE_SUCCESS = "ADD_CONTRACTOR_TYPE_SUCCESS";
export const ADD_CONTRACTOR_TYPE_FAIL = "ADD_CONTRACTOR_TYPE_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_CONTRACTOR_TYPE = "UPDATE_CONTRACTOR_TYPE";
export const UPDATE_CONTRACTOR_TYPE_SUCCESS = "UPDATE_CONTRACTOR_TYPE_SUCCESS";
export const UPDATE_CONTRACTOR_TYPE_FAIL = "UPDATE_CONTRACTOR_TYPE_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_CONTRACTOR_TYPE = "DELETE_CONTRACTOR_TYPE";
export const DELETE_CONTRACTOR_TYPE_SUCCESS = "DELETE_CONTRACTOR_TYPE_SUCCESS";
export const DELETE_CONTRACTOR_TYPE_FAIL = "DELETE_CONTRACTOR_TYPE_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
