/* PROJECTS */
export const GET_ADDRESS_STRUCTURE = "GET_ADDRESS_STRUCTURE";
export const GET_ADDRESS_STRUCTURE_SUCCESS = "GET_ADDRESS_STRUCTURE_SUCCESS";
export const GET_ADDRESS_STRUCTURE_FAIL = "GET_ADDRESS_STRUCTURE_FAIL";

/**
 * add PROJECT
 */
export const ADD_ADDRESS_STRUCTURE = "ADD_ADDRESS_STRUCTURE";
export const ADD_ADDRESS_STRUCTURE_SUCCESS = "ADD_ADDRESS_STRUCTURE_SUCCESS";
export const ADD_ADDRESS_STRUCTURE_FAIL = "ADD_ADDRESS_STRUCTURE_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_ADDRESS_STRUCTURE = "UPDATE_ADDRESS_STRUCTURE";
export const UPDATE_ADDRESS_STRUCTURE_SUCCESS = "UPDATE_ADDRESS_STRUCTURE_SUCCESS";
export const UPDATE_ADDRESS_STRUCTURE_FAIL = "UPDATE_ADDRESS_STRUCTURE_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_ADDRESS_STRUCTURE = "DELETE_ADDRESS_STRUCTURE";
export const DELETE_ADDRESS_STRUCTURE_SUCCESS = "DELETE_ADDRESS_STRUCTURE_SUCCESS";
export const DELETE_ADDRESS_STRUCTURE_FAIL = "DELETE_ADDRESS_STRUCTURE_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
