/* PROJECTS */
export const GET_PROJECT_DOCUMENT = "GET_PROJECT_DOCUMENT";
export const GET_PROJECT_DOCUMENT_SUCCESS = "GET_PROJECT_DOCUMENT_SUCCESS";
export const GET_PROJECT_DOCUMENT_FAIL = "GET_PROJECT_DOCUMENT_FAIL";

/**
 * add PROJECT
 */
export const ADD_PROJECT_DOCUMENT = "ADD_PROJECT_DOCUMENT";
export const ADD_PROJECT_DOCUMENT_SUCCESS = "ADD_PROJECT_DOCUMENT_SUCCESS";
export const ADD_PROJECT_DOCUMENT_FAIL = "ADD_PROJECT_DOCUMENT_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_PROJECT_DOCUMENT = "UPDATE_PROJECT_DOCUMENT";
export const UPDATE_PROJECT_DOCUMENT_SUCCESS = "UPDATE_PROJECT_DOCUMENT_SUCCESS";
export const UPDATE_PROJECT_DOCUMENT_FAIL = "UPDATE_PROJECT_DOCUMENT_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_PROJECT_DOCUMENT = "DELETE_PROJECT_DOCUMENT";
export const DELETE_PROJECT_DOCUMENT_SUCCESS = "DELETE_PROJECT_DOCUMENT_SUCCESS";
export const DELETE_PROJECT_DOCUMENT_FAIL = "DELETE_PROJECT_DOCUMENT_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
