/* PROJECTS */
export const GET_PROJECT_STAKEHOLDER = "GET_PROJECT_STAKEHOLDER";
export const GET_PROJECT_STAKEHOLDER_SUCCESS = "GET_PROJECT_STAKEHOLDER_SUCCESS";
export const GET_PROJECT_STAKEHOLDER_FAIL = "GET_PROJECT_STAKEHOLDER_FAIL";

/**
 * add PROJECT
 */
export const ADD_PROJECT_STAKEHOLDER = "ADD_PROJECT_STAKEHOLDER";
export const ADD_PROJECT_STAKEHOLDER_SUCCESS = "ADD_PROJECT_STAKEHOLDER_SUCCESS";
export const ADD_PROJECT_STAKEHOLDER_FAIL = "ADD_PROJECT_STAKEHOLDER_FAIL";

/**
 * Edit PROJECT
 */
export const UPDATE_PROJECT_STAKEHOLDER = "UPDATE_PROJECT_STAKEHOLDER";
export const UPDATE_PROJECT_STAKEHOLDER_SUCCESS = "UPDATE_PROJECT_STAKEHOLDER_SUCCESS";
export const UPDATE_PROJECT_STAKEHOLDER_FAIL = "UPDATE_PROJECT_STAKEHOLDER_FAIL";

/**
 * Delete PROJECT
 */
export const DELETE_PROJECT_STAKEHOLDER = "DELETE_PROJECT_STAKEHOLDER";
export const DELETE_PROJECT_STAKEHOLDER_SUCCESS = "DELETE_PROJECT_STAKEHOLDER_SUCCESS";
export const DELETE_PROJECT_STAKEHOLDER_FAIL = "DELETE_PROJECT_STAKEHOLDER_FAIL";

export const TOGGLE_UPDATE_LOADING = "TOGGLE_UPDATE_LOADING";
